# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
  fetchDepth: 0
- task: UseNode@1
  inputs:
    version: '18.x'

- script: |
    pnpm install
    pnpm build-storybook
    pnpm chromatic
  displayName: 'Run a multi-line script'
