# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
  fetchDepth: '0'
- task: UseNode@1
  inputs:
    version: '18.x'
- task: Cache@2
  inputs:
    key: 'pnpm | "$(Agent.OS)" | pnpm-lock.yaml'
    path: $(pnpm_config_cache)
  displayName: 'Cache pnpm'
- script: |
    curl -f https://get.pnpm.io/v9.4.0.js | node - add --global pnpm@9.4.0
    pnpm config set store-dir $(pnpm_config_cache)
  displayName: "Setup pnpm"

- script: pnpm install
- script: pnpm build-storybook
- script: pnpm chromatic
